import json
import os
import sqlite3
from datetime import datetime, timezone

from services.env_loader import load_env_file

load_env_file()
DATABASE_URL = os.getenv("DATABASE_URL") or os.getenv("SUPABASE_DB_URL")
DB_PATH = os.getenv("KYC_DB_PATH", "data/kyc_records.db")
DB_BACKEND = "postgres" if DATABASE_URL else "sqlite"


def get_connection():
    if DB_BACKEND == "postgres":
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:
            raise RuntimeError(
                "Postgres database configured, but psycopg is not installed. "
                "Run `pip install -r requirements.txt`."
            ) from exc

        return psycopg.connect(DATABASE_URL, row_factory=dict_row)

    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    connection = sqlite3.connect(DB_PATH)
    connection.row_factory = sqlite3.Row
    return connection


def placeholder():
    return "%s" if DB_BACKEND == "postgres" else "?"


def init_db():
    with get_connection() as connection:
        if DB_BACKEND == "postgres":
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS kyc_records (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    created_at TEXT NOT NULL,
                    name TEXT NOT NULL,
                    dob TEXT NOT NULL,
                    aadhaar_last4 TEXT NOT NULL,
                    aadhaar_masked TEXT,
                    pan_masked TEXT,
                    document_path TEXT,
                    aadhaar_document_path TEXT,
                    aadhaar_storage_path TEXT,
                    pan_document_path TEXT,
                    pan_storage_path TEXT,
                    selfie_path TEXT,
                    selfie_storage_path TEXT,
                    verification_source TEXT,
                    liveness_completed INTEGER NOT NULL DEFAULT 0,
                    decision TEXT NOT NULL,
                    face_match INTEGER NOT NULL DEFAULT 0,
                    face_score DOUBLE PRECISION,
                    face_distance DOUBLE PRECISION,
                    face_model TEXT,
                    face_detector TEXT,
                    face_metric TEXT,
                    face_orientation TEXT,
                    face_candidate TEXT,
                    upload_metadata TEXT,
                    debug_metadata TEXT
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    created_at TEXT NOT NULL,
                    name TEXT NOT NULL,
                    email TEXT NOT NULL UNIQUE,
                    password_hash TEXT NOT NULL
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS uploaded_files (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    created_at TEXT NOT NULL,
                    kind TEXT NOT NULL,
                    local_path TEXT,
                    storage_bucket TEXT,
                    storage_path TEXT,
                    storage_url TEXT,
                    storage_error TEXT,
                    metadata TEXT
                )
                """
            )
            ensure_kyc_upload_columns(connection)
            return

        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS kyc_records (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT NOT NULL,
                name TEXT NOT NULL,
                dob TEXT NOT NULL,
                aadhaar_last4 TEXT NOT NULL,
                aadhaar_masked TEXT,
                pan_masked TEXT,
                document_path TEXT,
                aadhaar_document_path TEXT,
                aadhaar_storage_path TEXT,
                pan_document_path TEXT,
                pan_storage_path TEXT,
                selfie_path TEXT,
                selfie_storage_path TEXT,
                verification_source TEXT,
                liveness_completed INTEGER NOT NULL DEFAULT 0,
                decision TEXT NOT NULL,
                face_match INTEGER NOT NULL DEFAULT 0,
                face_score REAL,
                face_distance REAL,
                face_model TEXT,
                face_detector TEXT,
                face_metric TEXT,
                face_orientation TEXT,
                face_candidate TEXT,
                upload_metadata TEXT,
                debug_metadata TEXT
            )
            """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT NOT NULL,
                name TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL
            )
                """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS uploaded_files (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT NOT NULL,
                kind TEXT NOT NULL,
                local_path TEXT,
                storage_bucket TEXT,
                storage_path TEXT,
                storage_url TEXT,
                storage_error TEXT,
                metadata TEXT
            )
            """
        )
        ensure_kyc_upload_columns(connection)


def ensure_kyc_upload_columns(connection):
    columns = {
        "aadhaar_document_path": "TEXT",
        "aadhaar_storage_path": "TEXT",
        "pan_document_path": "TEXT",
        "pan_storage_path": "TEXT",
        "selfie_path": "TEXT",
        "selfie_storage_path": "TEXT",
        "upload_metadata": "TEXT",
    }
    if DB_BACKEND == "postgres":
        for column, column_type in columns.items():
            connection.execute(f"ALTER TABLE kyc_records ADD COLUMN IF NOT EXISTS {column} {column_type}")
        return

    existing_columns = {
        row["name"] if isinstance(row, sqlite3.Row) else row[1]
        for row in connection.execute("PRAGMA table_info(kyc_records)").fetchall()
    }
    for column, column_type in columns.items():
        if column not in existing_columns:
            connection.execute(f"ALTER TABLE kyc_records ADD COLUMN {column} {column_type}")


def create_user(name, email, password_hash):
    init_db()
    created_at = datetime.now(timezone.utc).isoformat()
    with get_connection() as connection:
        if DB_BACKEND == "postgres":
            row = connection.execute(
                """
                INSERT INTO users (created_at, name, email, password_hash)
                VALUES (%s, %s, %s, %s)
                RETURNING id
                """,
                (created_at, name, email, password_hash),
            ).fetchone()
            return row["id"]

        cursor = connection.execute(
            """
            INSERT INTO users (created_at, name, email, password_hash)
            VALUES (?, ?, ?, ?)
            """,
            (created_at, name, email, password_hash),
        )
        return cursor.lastrowid


def create_uploaded_file_record(upload_metadata, extra_metadata=None):
    init_db()
    upload_metadata = upload_metadata or {}
    extra_metadata = extra_metadata or {}
    values = (
        datetime.now(timezone.utc).isoformat(),
        upload_metadata.get("kind") or "unknown",
        upload_metadata.get("local_path"),
        upload_metadata.get("storage_bucket"),
        upload_metadata.get("storage_path"),
        upload_metadata.get("storage_url"),
        upload_metadata.get("storage_error"),
        json.dumps(extra_metadata),
    )

    with get_connection() as connection:
        if DB_BACKEND == "postgres":
            row = connection.execute(
                """
                INSERT INTO uploaded_files (
                    created_at,
                    kind,
                    local_path,
                    storage_bucket,
                    storage_path,
                    storage_url,
                    storage_error,
                    metadata
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id
                """,
                values,
            ).fetchone()
            return row["id"]

        cursor = connection.execute(
            """
            INSERT INTO uploaded_files (
                created_at,
                kind,
                local_path,
                storage_bucket,
                storage_path,
                storage_url,
                storage_error,
                metadata
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            values,
        )
        return cursor.lastrowid


def find_user_by_email(email):
    init_db()
    marker = placeholder()
    with get_connection() as connection:
        return connection.execute(
            f"""
            SELECT id, created_at, name, email, password_hash
            FROM users
            WHERE lower(email) = lower({marker})
            """,
            (email,),
        ).fetchone()


def create_kyc_record(
    user,
    ocr_aadhaar,
    ocr_pan,
    face_result,
    document_path,
    source_type,
    liveness_completed,
    upload_metadata=None,
):
    init_db()
    upload_metadata = upload_metadata or {}
    aadhaar_upload = upload_metadata.get("aadhaar") or {}
    pan_upload = upload_metadata.get("pan") or {}
    selfie_upload = upload_metadata.get("selfie") or {}

    metadata = {
        "approve_threshold": face_result.get("approve_threshold"),
        "manual_threshold": face_result.get("manual_threshold"),
        "error": face_result.get("error"),
        "liveness": face_result.get("liveness"),
    }

    values = (
        datetime.now(timezone.utc).isoformat(),
        user.get("name"),
        user.get("dob"),
        user.get("aadhaar_last4"),
        ocr_aadhaar.get("masked_number"),
        mask_identifier(ocr_pan.get("pan_number")) if ocr_pan.get("pan_number") else None,
        document_path,
        aadhaar_upload.get("local_path"),
        aadhaar_upload.get("storage_path"),
        pan_upload.get("local_path"),
        pan_upload.get("storage_path"),
        selfie_upload.get("local_path"),
        selfie_upload.get("storage_path"),
        source_type,
        1 if liveness_completed else 0,
        face_result.get("decision", "REJECTED"),
        1 if face_result.get("match") else 0,
        face_result.get("score"),
        face_result.get("distance"),
        face_result.get("model"),
        face_result.get("detector"),
        face_result.get("metric"),
        face_result.get("orientation"),
        face_result.get("candidate"),
        json.dumps(upload_metadata),
        json.dumps(metadata),
    )

    with get_connection() as connection:
        if DB_BACKEND == "postgres":
            row = connection.execute(
                """
                INSERT INTO kyc_records (
                    created_at,
                    name,
                    dob,
                    aadhaar_last4,
                    aadhaar_masked,
                    pan_masked,
                    document_path,
                    aadhaar_document_path,
                    aadhaar_storage_path,
                    pan_document_path,
                    pan_storage_path,
                    selfie_path,
                    selfie_storage_path,
                    verification_source,
                    liveness_completed,
                    decision,
                    face_match,
                    face_score,
                    face_distance,
                    face_model,
                    face_detector,
                    face_metric,
                    face_orientation,
                    face_candidate,
                    upload_metadata,
                    debug_metadata
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id
                """,
                values,
            ).fetchone()
            return row["id"]

        cursor = connection.execute(
            """
            INSERT INTO kyc_records (
                created_at,
                name,
                dob,
                aadhaar_last4,
                aadhaar_masked,
                pan_masked,
                document_path,
                aadhaar_document_path,
                aadhaar_storage_path,
                pan_document_path,
                pan_storage_path,
                selfie_path,
                selfie_storage_path,
                verification_source,
                liveness_completed,
                decision,
                face_match,
                face_score,
                face_distance,
                face_model,
                face_detector,
                face_metric,
                face_orientation,
                face_candidate,
                upload_metadata,
                debug_metadata
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            values,
        )
        return cursor.lastrowid


def mask_identifier(value):
    if not value:
        return None
    return f"XXXX XXXX {str(value)[-4:]}"
